config:
  selfUrl: https://eshop-st-gateway-public-web
  isOnK8s: "true"
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: Staging 
  redisHost: eshop-st-redis
  rabbitmqHost: eshop-st-rabbitmq
  elasticsearchHost: eshop-st-elasticsearch

reRoutes:
  identityService:
    url: http://eshop-st-identity
    dns: https://identity.eshoponabp.dev
  administrationService:
    url: http://eshop-st-administration
    dns: https://administration.eshoponabp.dev
  catalogService:
    url: http://eshop-st-catalog
    dns: https://catalog.eshoponabp.dev
  basketService:
    url: http://eshop-st-basket
    dns: https://basket.eshoponabp.dev
  orderingService:
    url: http://eshop-st-ordering
    dns: https://ordering.eshoponabp.dev
  cmskitService:
    url: http://eshop-st-cmskit
    dns: https://cmskit.eshoponabp.dev
  paymentService:
    url: http://eshop-st-payment
    dns: https://payment.eshoponabp.dev

ingress:
  host: eshop-st-gateway-web-public
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}