# Generated by Django 4.1.1 on 2022-09-29 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_imagegallery_trait_product_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='media',
        ),
        migrations.AddField(
            model_name='imagegallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='product.product'),
        ),
        migrations.AddField(
            model_name='market',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market', to='product.product'),
        ),
    ]
