# Generated by Django 4.1.1 on 2022-09-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_market_remove_product_media_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagegallery',
            name='product',
        ),
        migrations.RemoveField(
            model_name='market',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.market'),
        ),
        migrations.AddField(
            model_name='product',
            name='media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.imagegallery'),
        ),
    ]
