# Generated by Django 4.1.1 on 2022-10-03 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_imagegallery_product_remove_market_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='position',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
