# Generated by Django 4.1.1 on 2022-10-04 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_category_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='highest_bid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='last_sale',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='lowest_ask',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='market',
            name='sales_ever',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
