# Generated by Django 4.1.1 on 2022-10-04 06:22

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_market_highest_bid_market_last_sale_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='traits',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='product.trait'),
        ),
        migrations.AddField(
            model_name='trait',
            name='label',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='trait',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trait',
            name='size_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
        migrations.AddField(
            model_name='trait',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=[], size=None),
        ),
    ]
