# Generated by Django 4.1.1 on 2022-10-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_traits_trait_label_trait_release_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True)),
            ],
            options={
                'ordering': ('slug',),
            },
        ),
    ]
