# Generated by Django 4.1.1 on 2022-10-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_productattribute_productattributevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='product',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='product',
            field=models.ManyToManyField(related_name='attributes', to='product.product'),
        ),
    ]
