# Generated by Django 4.1.1 on 2022-10-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_remove_productattributevalue_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattributevalue',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, related_name='attributes', to='product.product'),
        ),
    ]
