# Generated by Django 4.1.1 on 2022-10-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_productattributevalue_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='field_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
