# Generated by Django 4.1.1 on 2022-10-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_productattribute_field_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
