# Generated by Django 4.1.1 on 2022-10-04 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_brand_product_primary_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='product_type',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='product_type',
            field=models.ManyToManyField(to='product.producttype'),
        ),
    ]
