# Generated by Django 4.1.1 on 2022-10-04 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_remove_productattributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattributevalue',
            name='attribute',
        ),
        migrations.AddField(
            model_name='productattributevalue',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='product.productattribute'),
        ),
    ]
