export const ButtonStyles = {
  baseStyle: {
    fontFamily: 'proximaNova',
    fontWeight: 700,
    letterSpacing: '0px',
    margin: '4px 2px',
  },
  sizes: {},
  variants: {
    continue: {
      color: '#0f0f0f',
      border: 'solid #0f0f0f 1px',
      h: '50px',
      margin: '4px 2px',
      minW: '50px',
      w: '99%',
      borderRadius: '2px',
      padding: '0px',
      fontSize: '16px',
      bg: '#fff',
    },
    authentication: {
      w: 'full',
      h: '50px',
      fontSize: '14px',
      letterSpacing: '0.5px',
      padding: '0px',
      background: '#0f0f0f',
      color: '#fff',
      border: 'none',
    },
    accessToggle: {
      borderRadius: '2px',
      background: '#fff',
      w: '50%',
      border: '2px solid transparent',
      borderBottom: '2px solid #e0e0e0',
      color: '#616161',
      fontWeight: 600,
      fontSize: '14px',
      padding: '14px',
    },
    signup: {
      borderRadius: '0',
      appearance: 'none',
      variant: 'solid',
      bg: 'neutral.600',
      color: 'white',
      _hover: { bg: 'neutral.black', color: 'neutral.200' },
      h: '32px',
      w: 'auto',
      lineHeight: '1.375',
      fontWeight: 'semibold',
      fontFamily: 'suisseIntlRegular',
      minH: 'auto',
    },
    login: {
      display: 'inline-flex',
      borderRadius: '0',
      _hover: { bgColor: 'neutral.black', color: 'neutral.white' },
      lineHeight: '1.375',
      fontWeight: 'semibold',
      fontFamily: 'suisseIntlRegular',
      border: '1px solid',
      borderColor: 'neutral.black',
      color: 'neutral.600',
      bg: 'transparent',
      h: '32px',
    },
    suggestionSubmit: {
      p: '16px 16px',
      border: '0px solid transparent',
      borderRadius: '3px',
      font: 'normal 700 15px',
      bg: 'black',
      color: 'white',
    },
    green: {
      fontFamily: 'suisseIntlRegular',
      borderRadius: '0',
      minW: '260px',
      m: { base: '0 auto 20px', lg: '0 10px', xl: '0 20px 20px' },
      bg: '#006340',
      p: '15px 25px 16px',
      color: '#fff',
      letterSpacing: '-.75px',
      _hover: {
        bg: 'rgba(0,99,64,.85)',
      },
      h: '55px',
    },
    marketActivity: {
      borderRadius: '0',
      _hover: { bgColor: 'neutral.black', color: 'neutral.white' },
      border: '1px solid',
      borderColor: 'neutral.black',
      fontWeight: 'semibold',
      fontFamily: 'suisseIntlRegular',
      h: '34px',
      w: '83px',
      minW: {
        base: '110px',
        md: '110px',
        lg: 'auto',
      },
      fontSize: 'sm',
      fontStyle: 'normal',
      m: '1',
      p: { sm: '1rem 0.5rem' },
    },
  },
  defaultProps: {},
};
