config:
  selfUrl: # https://eshop-st-cmskit
  corsOrigins: # https://eshop-st-gateway-web,https://eshop-st-gateway-public-web
  connectionStrings:
    cmskitService: #
    administrationService: #
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
    metadataAddress: http://eshop-st-keycloak:8080
    swaggerClientId: WebGateway_Swagger
  remoteServices:
    abpIdentityBaseUrl: #
  dotnetEnv: Staging
  redisHost: eshop-st-redis
  rabbitmqHost: eshop-st-rabbitmq
  elasticsearchHost: eshop-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

synchedCommunication:
  grantType: # "client_credentials"
  clientId: # 
  clientSecret: #
  authority: # "https://eshop-st-authserver"
  scope: # "IdentityService"

ingress:
  host: eshop-st-cmskit
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/service-cmskit
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    