config:
  selfUrl: # https://eshop-st-gateway-web
  corsOrigins: # localhost:4200
  isOnK8s: "true"
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchHost: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8
reRoutes:
  identityService:
    url: http://eshop-st-identity
    dns: https://identity.eshoponabp.dev
  administrationService:
    url: http://eshop-st-administration
    dns: https://administration.eshoponabp.dev
  catalogService:
    url: http://eshop-st-catalog
    dns: https://catalog.eshoponabp.dev
  orderingService:
    url: http://eshop-st-ordering
    dns: https://ordering.eshoponabp.dev
  cmskitService:
    url: http://eshop-st-cmskit
    dns: https://cmskit.eshoponabp.dev
    
ingress:
  host: # eshop-st-gateway-web
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/gateway-web
  tag: latest
  pullPolicy: IfNotPresent

env: {}